source "https://rubygems.org"

gem 'sinatra', '~> 1.4', '>= 1.4.7'
gem 's3', '~> 0.3.24'
gem 'toml', '~> 0.1.2'
gem 'dotenv', '~> 2.1', '>= 2.1.1'
gem 'concurrent-ruby', '~> 1.0', '>= 1.0.2'
gem 'glorify', '~> 0.5.0'
